### ISSUE TITLE
Image links are broken on the ‘Remix Basics’ tutorial pages. 

### ISSUE THREAD

**Issue by salil-naik** [ethereum/remix-workshops#108]
<img width="280" alt="issue" src="https://user-images.githubusercontent.com/20141508/107269832-2b48ba00-6a70-11eb-9d34-c3f1dbadcf4d.png">

**Comment by ryestew** [comment]
@salil-naik Thank you so much for opening this Issue. We really appreciate you catching this problem.

**Comment by salil-naik** [comment]
> @salil-naik Thank you so much for opening this Issue. We really appreciate you catching this problem.

@ryestew you are welcome. 😄
